// Swedish interface strings. Keys that are missing here fall back to English.
export const sv = {
  'app.name': 'Mathsheet',
  'app.lang': 'sv',
  'app.skip': 'Hoppa till arbetsbladet',
  'app.language': 'Språk',

  'file.new': 'Nytt',
  'file.open': 'Öppna',
  'file.save': 'Spara JSON',
  'file.export': 'Exportera HTML',
  'file.exportEmpty': 'Lägg till en uppgift innan du exporterar',
  'status.unsaved': 'Osparade ändringar',
  'status.clean': 'Inga osparade ändringar',

  'tab.custom': 'Skriv en uppgift',
  'tab.generate': 'Generera',
  'tab.list': 'Lägg till uppgifter',

  'form.statement': 'Uppgift',
  'form.answer': 'Svar',
  'form.solution': 'Lösning (valfritt)',
  'form.points': 'Poäng',
  'form.tags': 'Taggar, avgränsade med kommatecken',
  'form.add': 'Lägg till i arbetsbladet',
  'form.save': 'Spara ändringar',
  'form.cancel': 'Avbryt',
  'form.editing': 'Redigerar uppgift {n}',
  'form.hint': 'Skriv matematik mellan dollartecken: $x^2$ i löptext, $$x^2$$ på en egen rad. Skriv \\$ för ett vanligt dollartecken.',
  'form.preview': 'Förhandsvisning',
  'form.previewEmpty': 'Den färdiga uppgiften visas här.',
  'form.snippets': 'Infoga matematik',
  'form.statementRequired': 'Skriv uppgiftstexten först.',
  'form.mathError': 'Kontrollera formeln: {msg}',

  'json.edit': 'Redigera JSON',
  'json.back': 'Tillbaka till arbetsbladet',
  'json.title': 'Redigera arbetsbladet som JSON',
  'json.intro': 'Ändringarna gäller först när du klickar på Tillämpa, och bara om filen klarar valideringen. Genererade uppgifter behåller sin generator, sina inställningar och sitt frö.',
  'json.label': 'Arbetsbladets JSON',
  'json.unchanged': 'Inga ändringar än.',
  'json.valid': 'Giltig. Redo att tillämpas.',
  'json.invalid': 'Går inte att tillämpa än:',
  'json.apply': 'Tillämpa ändringar',
  'json.revert': 'Återställ',
  'json.applied': 'JSON tillämpad',
  'confirm.discardJson': 'Du har JSON-ändringar som inte har tillämpats. Vill du kasta dem?',

  'export.title': 'Exportera arbetsblad',
  'export.intro': 'Skapar en HTML-fil som du kan mejla, ladda upp till en lärplattform eller skriva ut. Den behöver inget JavaScript.',
  'export.answerKey': 'Facit',
  'export.key': 'Facit',
  'export.includeKey': 'Ta med facit',
  'export.includeSolutions': 'Ta med fullständiga lösningar',
  'export.newPage': 'Börja facit på en ny sida',
  'export.content': 'Innehåll',
  'export.showPoints': 'Visa poäng',
  'export.shuffle': 'Blanda uppgifternas ordning',
  'export.fonts': 'Matematiktypsnitt',
  'export.fontsCdn': 'Hämta från ett CDN',
  'export.fontsCdnHint': 'Minsta filen. Formlerna ser rätt ut bara när läsaren är online.',
  'export.fontsEmbed': 'Bädda in i filen',
  'export.fontsEmbedHint': 'Ger cirka 400 KB större fil. Fungerar offline.',
  'export.source': 'Öppna igen senare',
  'export.embedSource': 'Bädda in arbetsbladets data i filen',
  'export.embedSourceHint': 'Gör att du kan öppna HTML-filen i Mathsheet igen. Den innehåller alla svar och lösningar, så eleverna skulle kunna läsa dem.',
  'export.download': 'Ladda ner HTML',
  'export.preview': 'Förhandsvisa',
  'export.close': 'Stäng',
  'export.building': 'Förbereder filen …',
  'export.done': 'Sparade {name}',
  'export.failed': 'Exporten gick inte att skapa ({msg}). Kontrollera att sidan körs via en webbserver.',
  'export.popup': 'Tillåt popup-fönster för att se förhandsvisningen.',
  'export.mathErrors.one': '{n} formel kunde inte visas och står som vanlig text.',
  'export.mathErrors.other': '{n} formler kunde inte visas och står som vanlig text.',

  'gen.generator': 'Typ av uppgift',
  'gen.settings': 'Inställningar',
  'gen.count': 'Antal',
  'gen.points': 'Poäng per uppgift',
  'gen.button': 'Generera uppgifter',
  'gen.countInvalid': 'Ange ett tal från 1 till {max}.',
  'gen.noneNew': 'Inga nya uppgifter gick att skapa med de här inställningarna. Vidga talintervallet eller ändra ett val.',

  'sheet.titlePlaceholder': 'Arbetsblad utan namn',
  'sheet.subjectPlaceholder': 'Ämne eller klass',
  'sheet.name': 'Namn',
  'sheet.date': 'Datum',
  'sheet.problems': 'Uppgifter',
  'sheet.worksheet': 'Arbetsblad',
  'sheet.noName': 'Arbetsblad utan namn',

  'controls.showAnswers': 'Visa svar här',
  'controls.nameDate': 'Rader för namn och datum',
  'controls.numbering': 'Numrering',
  'controls.language': 'Arbetsbladets språk',
  'controls.languageHint': 'Styr formuleringen av genererade uppgifter och etiketterna i exporterade filer. Uppgifter som redan finns behåller sin text.',
  'numbering.decimal': '1, 2, 3',
  'numbering.alpha': 'a, b, c',
  'numbering.roman': 'i, ii, iii',
  'numbering.none': 'Ingen',
  'controls.total.one': '{n} poäng totalt',
  'controls.total.other': '{n} poäng totalt',

  'empty.title': 'Inga uppgifter än',
  'empty.body': 'Skriv en uppgift till vänster, eller öppna exemplet för att se hur ett arbetsblad ser ut.',
  'empty.example': 'Öppna exempelarbetsblad',

  'problem.up': 'Flytta upp',
  'problem.down': 'Flytta ner',
  'problem.edit': 'Redigera',
  'problem.regenerate': 'Generera om',
  'problem.duplicate': 'Duplicera',
  'problem.delete': 'Ta bort',
  'problem.drag': 'Dra för att ändra ordning',
  'problem.generated': 'Genererad',
  'problem.edited': 'Ändrad för hand',
  'problem.label': 'Uppgift {n}',
  'problem.pts.one': '{n} p',
  'problem.pts.other': '{n} p',
  'problem.answer': 'Svar:',
  'problem.solution': 'Lösning:',
  'problem.tools': 'Åtgärder för uppgift {n}',

  'toast.added': 'Uppgiften har lagts till',
  'toast.generated.one': '{n} uppgift har lagts till',
  'toast.generated.other': '{n} uppgifter har lagts till',
  'toast.generatedFewer': 'La till {made} av {wanted}. De här inställningarna ger få olika uppgifter.',
  'toast.regenerateFailed': 'Uppgiften gick inte att generera om. Kontrollera generator och inställningar i JSON-filen.',
  'toast.updated': 'Uppgiften har uppdaterats',
  'toast.deleted': 'Uppgiften har tagits bort',
  'toast.undo': 'Ångra',
  'toast.fileSaved': 'Sparade {name}',
  'toast.loaded': 'Öppnade {title}',
  'toast.exampleFailed': 'Exemplet gick inte att läsa in. Kör mappen via en lokal webbserver (se README).',

  'banner.restore': 'Vill du återställa din senaste session? ”{title}”, {count}, sparad {when}.',
  'banner.restoreBtn': 'Återställ',
  'banner.discardBtn': 'Kasta',
  'banner.errorTitle': 'Filen gick inte att öppna.',
  'banner.dismiss': 'Stäng',
  'count.problem.one': '{n} uppgift',
  'count.problem.other': '{n} uppgifter',

  'confirm.regenerateEdited': 'Uppgiften har ändrats för hand. Vill du ersätta den med en ny genererad uppgift?',
  'confirm.discard': 'Du har osparade ändringar. Vill du kasta dem?',
  'worksheet.untitled': 'Arbetsblad utan namn',

  'error.noSource': 'HTML-filen innehåller ingen arbetsbladsdata. Bara filer som exporterats med ”Bädda in arbetsbladets data” kan öppnas igen.',
  'error.invalidJson': 'Filen är inte giltig JSON ({msg}).',
};
